
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - nw_laravel_app
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_stable_alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nw_laravel_app
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel_user_1
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"
    volumes:
      - db_laravel_app:/var/lib/mysql
    networks:
      - nw_laravel_app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_02
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8899:80"
    networks:
      - nw_laravel_app
    depends_on:
      - db


  frontend:
    image: node:latest
    container_name: frontend_app
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - nw_laravel_app
    depends_on:
      - app


networks:
  nw_laravel_app:

volumes:
  db_laravel_app:
